language: python

jdk: oraclejdk7

services:
  - elasticsearch
  - mysql

env:
  global:
    - PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - POSTGRES_USER=postgres
  matrix:
    - TOXENV=pep8
    - TOXENV=py27-nonhdfs

sudo: false

cache:
  - $HOME/.pip-cache

install:
  - pip install tox

before_script:
  - psql -c 'create database spotify;' -U postgres

  # allow ssh loopback
  - ssh-keygen -t rsa -N '' -C '' -f ~/.ssh/id_rsa
  - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  - ssh -o StrictHostKeyChecking=no localhost true

  # Create mysql database if possible but fail silently if not available.
  - mysql -e 'create database IF NOT EXISTS luigi_test;' -uroot || true

script:
  - tox --version
  - tox

branches:
  only:
    - master
